// utils/headlines.js
export const headlines = [
  "How [name] Became a Game-Changer in [location]",
  "Step Inside [name]: A Fresh Take on [location]'s Local Scene",
  "[location]'s Best-Kept Secret? It's [name]",
  "Meet [name] — Where Creativity Thrives in [location]",
  "The Smartest Move in [location]: Choosing [name]",
  "Why [name] is the Talk of the Town in [location]",
  "[name]: Merging Quality with Character in [location]",
  "Explore [name] — A New Standard for [location]",
  "[name] Sets a New Pace for Progress in [location]",
  "Inside [name]: The Vision Reshaping [location]",
  "Discover What Makes [name] Unforgettable in [location]",
  "The Buzz Around [name] in [location] Is Real",
  "Find Out Why [name] Turns Heads in [location]",
  "[name] Is Crafting Something Unique for [location]",
  "[name] Leads the Way with Innovation in [location]",
  "Unlock the Experience Everyone's Craving at [name], [location]",
  "How [name] Is Making Waves Across [location]",
  "[name] Redefines Everyday Excellence in [location]",
  "Your New Obsession in [location]? It’s [name]",
  "Locals in [location] Can’t Get Enough of [name]",
  "Step Into the Future with [name] in [location]",
  "[name] Combines Style and Simplicity for [location] Locals",
  "See Why [location] Is Turning to [name] for More",
  "Smart, Bold, and Local — That’s [name] in [location]",
  "[name] in [location]: Fresh Energy, Real Results",
];
